on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [ main ]
jobs:
  hello_world_job:
    runs-on: windows-latest
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build and Analyse
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          prow-commands: assign     
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm install eslint --global
      - id: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LANG: JS
        uses: applibgroup/HarmonyOs-build@v5.6
        continue-on-error: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: artifact
          path: ${{ github.workspace }}\result.json 
 
  
               
