name: "Pull Request Labeler"
on:
 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ] 
jobs:
 triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 
    env:
       PR_NUMBER: ${{ github.event.number }}     
 execute:
    runs-on: ubuntu-latest
    needs:  triage
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          prow-commands: '/area'
              
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
