name: "Pull Request Labeler"
on:
 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ] 
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 
    - name: Get Pull Request Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"    
      
      env:
       PR_NUMBER: ${{ github.event.number }}        
