name: "Pull Request Labeler"
on:
 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ] 
jobs:
 triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
   # - name: Get Pull Request Number
    #  id: pr
     # run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 
        
 execute:
    runs-on: ubuntu-latest
    needs:  triage
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          prow-commands:  '/assign 
            /unassign 
            /approve 
            /retitle 
            /area 
            /kind 
            /priority 
            /remove 
            /lgtm 
            /close 
            /reopen 
            /lock 
            /milestone 
            /hold 
            /cc 
            /uncc'   
      
      env:
       PR_NUMBER: ${{ github.event.number }} 
       github-token: "${{ secrets.GITHUB_TOKEN }}"
