name: "Pull Request Labeler"
on:
 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ] 
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1
        with:
          prow-commands: area
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
   # - name: Get Pull Request Number
    #  id: pr
     # run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 
      
      
      env:
       PR_NUMBER: ${{ github.event.number }}        
